FROM node:20-slim

WORKDIR /app

# Primero instalamos solo las dependencias de producción (muy rápido)
COPY package*.json ./
RUN npm install --omit=dev

# Copiamos el build generado por el Action (dist)
COPY dist ./dist

# Copiamos el resto de archivos del servidor (server.js, db.js, etc.)
COPY . .

EXPOSE 3001

CMD ["node", "server.js"]
