FROM node:20-slim

WORKDIR /app

# Copiamos TODOS los archivos ya procesados desde GitHub Actions
# Incluyendo node_modules (production) y dist
COPY . .

EXPOSE 3001

# No hay RUN npm install aquí. Todo viene ya listo del Action.
CMD ["node", "server.js"]
